enum ProjectTag {
  Vue = 'Vue',
  GraphQL = 'GraphQL',
  TypeScript = 'TypeScript',
  Git = 'Git',
  Node = 'Node.js',
  Python = 'Python',
  PythonLibs = 'Pandas/Numpy/Matplotlib',
  Jupyter = 'Jupyter Notebook',
  Tensorflow = 'Tensorflow',
  JavaScript = 'JavaScript (ES6)',
  CSS = 'CSS/SASS',
  Tailwind = 'TailwindCSS',
  Go = 'Go',
  Nuxt = 'Nuxt',
  Java = 'Java',
  GRPC = 'gRPC',
  Redis = 'Redis',
  PostgreSQL = 'PostgreSQL',
  Angular = 'Angular',
  SQL = 'SQL',
  Kotlin = 'Kotlin',
  Scala = 'Scala',
  Dart = 'Dart',
  JQuery = 'jQuery',
  Nginx = 'Nginx',
  Kafka = 'Kafka',
  React = 'React',
  MySQL = 'MySQL',
  Docker = 'Docker',
  Jenkins = 'Jenkins',
  SpringBoot = 'SpringBoot',
  MongoDB = 'MongoDB',
  Electron = 'Electron',
  Firebase = 'Firebase',
  Scikitlearn = 'Scikit-learn',
  Vim = 'Vim',
}

export default ProjectTag;
